### ISSUE TITLE
Dataset Loading Bug

### ISSUE THREAD

**Issue by yerbles** [gagolews/clustering-benchmarks#5]
Hi,

Thanks for putting this package together, I'm excited to take advantage of it but I seem to be unable to load datasets locally (stored in a subdirectory of the working directory) or by URL. The code chunk below gives the following error

```python
import clustbench
print(clustbench.__version__)

data_path = "./Datasets/"
battery = "wut"
dataset = "x2"
b = clustbench.load_dataset(battery, dataset, path=data_path)
```

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~\AppData\Local\Temp\2\ipykernel_40820\39654233.py in ()
      5 battery = "wut"
      6 dataset = "x2"
----> 7 b = clustbench.load_dataset(battery, dataset, path=data_path)

...\lib\site-packages\clustbench\load_dataset.py in load_dataset(battery, dataset, path, url, expanduser, expandvars, preprocess, random_state)
    139         try:
    140             f = base_name + ".labels%d.gz" % i
--> 141             ll = np.loadtxt(f, dtype="int")
    142             if ll.ndim != 1 or ll.shape[0] != data.shape[0]:
    143                 raise ValueError("Incorrect number of labels in '%s'." % f)

~\AppData\Roaming\Python\Python39\site-packages\numpy\lib\npyio.py in loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin, encoding, max_rows, like)
   1063             fname = os_fspath(fname)
   1064         if _is_string_like(fname):
-> 1065             fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
   1066             fencoding = getattr(fh, 'encoding', 'latin1')
   1067             fh = iter(fh)

~\AppData\Roaming\Python\Python39\site-packages\numpy\lib\_datasource.py in open(path, mode, destpath, encoding, newline)
    192 
    193     ds = DataSource(destpath)
--> 194     return ds.open(path, mode, encoding=encoding, newline=newline)
    195 
    196 

~\AppData\Roaming\Python\Python39\site-packages\numpy\lib\_datasource.py in open(self, path, mode, encoding, newline)
    529                                       encoding=encoding, newline=newline)
    530         else:
--> 531             raise IOError("%s not found." % path)
    532 
    533 

OSError: ./Datasets/wut\x2.labels2.gz not found
```

It seems like the try-except block used to iteratively load the labels within the `load_dataset()` function is stumbling when attempting to load the next, non-existent set of labels for any dataset, i.e. "wut/x2" only has "x2.labels0.gz" and "x2.labels1.gz", and an error is thrown for non-existent "x2.labels2.gz" instead of continuing.

A similar error occurs for me with the suggested URL option as well: `b = clustbench.load_dataset(battery, dataset, url="https://github.com/gagolews/clustering-data-v1/raw/v1.1.0")`

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~\AppData\Local\Temp\2\ipykernel_40820\2190751781.py in ()
----> 1 b = clustbench.load_dataset(battery, dataset, url="https://github.com/gagolews/clustering-data-v1/raw/v1.1.0")

c:\Users\yer002\Anaconda3\envs\TensorFlow\lib\site-packages\clustbench\load_dataset.py in load_dataset(battery, dataset, path, url, expanduser, expandvars, preprocess, random_state)
    139         try:
    140             f = base_name + ".labels%d.gz" % i
--> 141             ll = np.loadtxt(f, dtype="int")
    142             if ll.ndim != 1 or ll.shape[0] != data.shape[0]:
    143                 raise ValueError("Incorrect number of labels in '%s'." % f)

~\AppData\Roaming\Python\Python39\site-packages\numpy\lib\npyio.py in loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin, encoding, max_rows, like)
   1063             fname = os_fspath(fname)
   1064         if _is_string_like(fname):
-> 1065             fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
   1066             fencoding = getattr(fh, 'encoding', 'latin1')
   1067             fh = iter(fh)

~\AppData\Roaming\Python\Python39\site-packages\numpy\lib\_datasource.py in open(path, mode, destpath, encoding, newline)
    192 
    193     ds = DataSource(destpath)
--> 194     return ds.open(path, mode, encoding=encoding, newline=newline)
    195 
    196 

~\AppData\Roaming\Python\Python39\site-packages\numpy\lib\_datasource.py in open(self, path, mode, encoding, newline)
    529                                       encoding=encoding, newline=newline)
    530         else:
--> 531             raise IOError("%s not found." % path)
    532 
    533 

OSError: https://github.com/gagolews/clustering-data-v1/raw/v1.1.0/wut/x2.labels2.gz not found.
```

Thanks in advance!

**Comment by gagolews** [comment]
It seems that you are on Windows, so your path separator is `\`, not `/`.

Try:

```
data_path = ".\\Datasets"
```

**Comment by gagolews** [comment]
I've assumed that it should be a `FileNotFoundError`, whereas your environment generates an `OSError`. Fixed now.

**Comment by yerbles** [comment]
Thanks for the speedy response! Could something be wrong on my end? I updated my version of the package and still get the same error.

**Comment by gagolews** [comment]
Do you get the error using the URL or file name?
Because it seems you're on Windows, so in the latter case, you should use backslashes as path separators, e.g., `data_path = r".\Datasets"`

**Comment by gagolews** [comment]
If this does not work, can you try using this function (to help me with debugging)?

```python

def load_dataset(
    battery, dataset, path=None,
    url=None, expanduser=True, expandvars=True,
    preprocess=True, random_state=None
):
    """
    Load a benchmark dataset

    Reads a dataset named `battery/dataset.data.gz`
    (relative to `url` or the directory `path`)
    as well as all the corresponding labels
    (`battery/dataset.labels0.gz`, `battery/dataset.labels1.gz`, ...).

    Parameters
    ----------

    battery
        Name of the battery (dataset collection), e.g., ``"wut"`` or ``"other"``.

    dataset
        Dataset name, e.g., ``"x2"`` or ``"iris"``.

    path
        Mutually exclusive with `url`.
        Path to the directory containing the downloaded benchmark datasets
        suite. Defaults to the current working directory.

    url
        Mutually exclusive with `path`. For example,
        ``"https://github.com/gagolews/clustering-data-v1/raw/v1.1.0"``
        to get access to <https://github.com/gagolews/clustering-data-v1>,

    expanduser
        Whether to call ``os.path.expanduser`` on the file path.

    expandvars
        Whether to call ``os.path.expandvars`` on the file path.

    preprocess
        Whether to call :any:`preprocess_data` on the data matrix.

    random_state
        Seed of the random number generator; passed to :any:`preprocess_data`.


    Returns
    -------

    benchmark
        A named tuple with the following elements:

        battery
            Same as the `battery` argument.

        dataset
            Same as the `dataset` argument.

        description
            Contents of the description file.

        data : ndarray
            Data matrix.

        labels : list
            A list consisting of the label vectors.

        n_clusters : ndarray
            The corresponding cluster counts:
            ``n_clusters[i]`` is equal to ``max(n_clusters[i])``.

    Examples
    --------

    >>> import os.path
    >>> import clustbench
    >>> # load from a local library (a manually downloaded suite)
    >>> data_path = os.path.join("~", "Projects", "clustering-data-v1")  # up to you
    >>> wut_x2 = clustbench.load_dataset("wut", "x2", path=data_path)
    >>> print(wut_x2.battery, wut_x2.dataset)
    >>> print(wut_x2.description)
    >>> print(wut_x2.data, wut_x2.labels)
    >>> # load from GitHub (slow...):
    >>> data_url = "https://github.com/gagolews/clustering-data-v1/raw/v1.1.0"
    >>> wut_smile = clustbench.load_dataset("wut", "smile", url=data_url)
    >>> print(wut_smile.data, wut_smile.labels)
    """
    if url is not None and path is not None:
        raise ValueError("`url` and `path` are mutually exclusive.")

    if url is not None:
        base_name = url + "/" + battery + "/" + dataset
    else:
        if path is None: path = "."
        base_name = os.path.join(path, battery, dataset)
        if expanduser: base_name = os.path.expanduser(base_name)
        if expandvars: base_name = os.path.expandvars(base_name)

    data_file = base_name + ".data.gz"
    data = np.loadtxt(data_file, ndmin=2)

    if data.ndim != 2:
        raise ValueError("Not a matrix.")

    if preprocess:
        data = preprocess_data(data, random_state=random_state)

    labels = []
    i = 0
    while True:
        try:
            f = base_name + ".labels%d.gz" % i
            ll = np.loadtxt(f, dtype="int")
            if ll.ndim != 1 or ll.shape[0] != data.shape[0]:
                raise ValueError("Incorrect number of labels in '%s'." % f)

            labels.append(ll)
            i += 1
        except (IOError, OSError):
            # this could be done better with glob.glob for local files,
            # but not for remote URLs
            break

    n_clusters = np.array([np.max(ll) for ll in labels])

    with np.DataSource().open(base_name + ".txt", "r") as readme_file:
        description = readme_file.read()

    RetClass = namedtuple(
        "ClusteringBenchmark",
        ["battery", "dataset", "description", "data", "labels", "n_clusters"]
    )
    return RetClass(
        battery=battery,
        dataset=dataset,
        description=description,
        data=data,
        labels=labels,
        n_clusters=n_clusters,
    )
```

**Comment by yerbles** [comment]
Still getting the error for both URL and local. Backslash didn't change the error, and using the function you provided I got the following:

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~\AppData\Local\Temp\2\ipykernel_40820\1448089098.py in ()
      2 battery = "wut"
      3 dataset = "x2"
----> 4 b = clustbench.load_dataset(battery, dataset, url="https://github.com/gagolews/clustering-data-v1/raw/v1.1.0")
      5 # b = clustbench.load_dataset(battery, dataset, path=data_path)

...\lib\site-packages\clustbench\load_dataset.py in load_dataset(battery, dataset, path, url, expanduser, expandvars, preprocess, random_state)
    139         try:
    140             f = base_name + ".labels%d.gz" % i
--> 141             ll = np.loadtxt(f, dtype="int")
    142             if ll.ndim != 1 or ll.shape[0] != data.shape[0]:
    143                 raise ValueError("Incorrect number of labels in '%s'." % f)

~\AppData\Roaming\Python\Python39\site-packages\numpy\lib\npyio.py in loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin, encoding, max_rows, like)
   1063             fname = os_fspath(fname)
   1064         if _is_string_like(fname):
-> 1065             fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
   1066             fencoding = getattr(fh, 'encoding', 'latin1')
   1067             fh = iter(fh)

~\AppData\Roaming\Python\Python39\site-packages\numpy\lib\_datasource.py in open(path, mode, destpath, encoding, newline)
    192 
    193     ds = DataSource(destpath)
--> 194     return ds.open(path, mode, encoding=encoding, newline=newline)
    195 
    196 

~\AppData\Roaming\Python\Python39\site-packages\numpy\lib\_datasource.py in open(self, path, mode, encoding, newline)
    529                                       encoding=encoding, newline=newline)
    530         else:
--> 531             raise IOError("%s not found." % path)
    532 
    533 

OSError: https://github.com/gagolews/clustering-data-v1/raw/v1.1.0/wut/x2.labels2.gz not found.
1.1.2
```

**Comment by gagolews** [comment]
Thanks for your patience; what about the following?

```python
def load_dataset(
    battery, dataset, path=None,
    url=None, expanduser=True, expandvars=True,
    preprocess=True, random_state=None
):
    if url is not None and path is not None:
        raise ValueError("`url` and `path` are mutually exclusive.")

    if url is not None:
        base_name = url + "/" + battery + "/" + dataset
    else:
        if path is None: path = "."
        base_name = os.path.join(path, battery, dataset)
        if expanduser: base_name = os.path.expanduser(base_name)
        if expandvars: base_name = os.path.expandvars(base_name)

    data_file = base_name + ".data.gz"
    data = np.loadtxt(data_file, ndmin=2)

    if data.ndim != 2:
        raise ValueError("Not a matrix.")

    if preprocess:
        data = preprocess_data(data, random_state=random_state)

    labels = []
    i = 0
    while True:
        f = base_name + ".labels%d.gz" % i
        if not np.DataSource().exists(f):
            break
            
        ll = np.loadtxt(f, dtype="int")
        if ll.ndim != 1 or ll.shape[0] != data.shape[0]:
            raise ValueError("Incorrect number of labels in '%s'." % f)

        labels.append(ll)
        i += 1

    n_clusters = np.array([np.max(ll) for ll in labels])

    with np.DataSource().open(base_name + ".txt", "r") as readme_file:
        description = readme_file.read()

    RetClass = namedtuple(
        "ClusteringBenchmark",
        ["battery", "dataset", "description", "data", "labels", "n_clusters"]
    )
    return RetClass(
        battery=battery,
        dataset=dataset,
        description=description,
        data=data,
        labels=labels,
        n_clusters=n_clusters,
    )
```

And then:

```python
import numpy as np
from collections import namedtuple
from clustbench import preprocess_data
load_dataset("wut", "x2", url="https://github.com/gagolews/clustering-data-v1/raw/v1.1.0")
```

**Comment by yerbles** [comment]
Works like a charm for URL and local. Thanks so much!

**Comment by gagolews** [comment]
Thanks. I've uploaded v1.1.4 to pypi.
